### ISSUE TITLE
on_message description is: ReferenceError: identifier 'cell' undefined

### ISSUE THREAD

**Issue by 7x0** [lyxhh/lxhToolHTTPDecrypt#1]
一直报这个错，请问是什么原因造成的？

**Comment by lyxhh** [comment]
已修复了 代码晚点上传，

**Comment by kingz40o** [comment]
[ERROR] on_message description is: Error: Implementation for getInstance expected return value compatible with 'com.skyland.app.frame.AppConfig'.
