### ISSUE TITLE
找加解密函数有那些思路？

### ISSUE THREAD

**Issue by SRW-OG** [lyxhh/lxhToolHTTPDecrypt#11]
如题

**Comment by SRW-OG** [comment]
一般通讯加密的app也做了代码混淆和加壳，按照通讯的参数查找函数，查不到。

**Comment by lyxhh** [comment]
首先你要明白代码混淆  混淆的是什么，混淆的只是开发者自己写的方法跟类 名，但是JDK的API这些他是不会被混淆的，我们就可以hook这些方法根据打印的堆栈去定位加解密类。
对于壳来说 HTTPDecrypt依旧可以工作。
