### ISSUE TITLE
回显中文乱码，再次加密的时候也是按照乱码的中文进行加密的

### ISSUE THREAD

**Issue by ck00004** [lyxhh/lxhToolHTTPDecrypt#13]
回显中文乱码，再次加密的时候也是按照乱码的中文进行加密的

一个例子
{"usr_token":"111111111111111111","isRoot":"Y","appPackage":"com.xxka.xxykt","networkTyp":"1","netServiceMer":"","deviceMod":"MuMu","characterSet":"02","plat":"0","contentTyp":"text/html","locationCity":"","start_day":"2019年11月","deviceLanguage":"zh","fingerData":"","locationProvince":"","locationData":"","locationCountry":"","userNo":"10000000000000101","opSys":"0","channel":"0","ipAddress":"10.0.3.15","clientVer":"1.1.0","time":"2019/12/3 20:42:15","pageSize":"10","locationXY":"11111111111111|11111111111111","pageNo":"1","appHash":"11111111111111","isEmulator":"N","crdType":"1","deviceID":"520000000131673","opSysVer":"6.0.1"}
加密后再次解密之后
{"usr_token":"111111111111111111","isRoot":"Y","appPackage":"com.xxka.xxykt","networkTyp":"1","netServiceMer":"","deviceMod":"MuMu","characterSet":"02","plat":"0","contentTyp":"text/html","locationCity":"","start_day":"2019t11\x08","deviceLanguage":"zh","fingerData":"","locationProvince":"","locationData":"","locationCountry":"","userNo":"10000000000000101","opSys":"0","channel":"0","ipAddress":"10.0.3.15","clientVer":"1.1.0","time":"2019/12/3 20:42:15","pageSize":"10","locationXY":"11111111111111|11111111111111","pageNo":"1","appHash":"11111111111111","isEmulator":"N","crdType":"1","deviceID":"520000000131673","opSysVer":"6.0.1"}

**Comment by lyxhh** [comment]
好的，明天我看看哈，感谢提交。

**Comment by lyxhh** [comment]
已修复,请更新Burp插件，如果您测试通过，请关闭此issue。

**Comment by ck00004** [comment]
已修复
