### ISSUE TITLE
[ERROR] frida-server No Running or port no forward....please check.

### ISSUE THREAD

**Issue by akkuman** [lyxhh/lxhToolHTTPDecrypt#2]
用usb连接设备，frida-ps -U 工作正常，这个无法连接到设备

**Comment by akkuman** [comment]
请求合并pr

**Comment by lyxhh** [comment]
抱歉，无法合并，你将更改frida端口的功能移除了，这使的当遇到一些反调试时，HTTPDecrypt 将无法工作，不符合我的想法。------------------ 原始邮件 ------------------
发件人: "akkuman"<notifications@github.com>
发送时间: 2019年5月9日(星期四) 晚上7:11
收件人: "lyxhh/lxhToolHTTPDecrypt"<lxhToolHTTPDecrypt@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [lyxhh/lxhToolHTTPDecrypt] [ERROR] frida-server No Running orport no forward....please check. (#2)



请求合并pr
 
&mdash;

**Comment by akkuman** [comment]
这个和反调试无关吧，就算进程查看端口27042，但监听的是本机的，转发的是 android 机上的，比如 android 机器上 frida-server 监听12345 端口，只要转发 12345 端口到本机的 27042 端口不就行了吗

**Comment by lyxhh** [comment]
经过测试，确实是这样的 一直以来我都是forward相同端口，没有关注这个，但是你的写法涉及到两个手机以上就会发生问题了，并且我的写法我还未发现任何问题，没有一个必须合并的理由。

**Comment by akkuman** [comment]
你的写法在我这边就跑不起来，如果不进行 forward 的话，但是 frida 官方的使用文档并没有一定需要转发端口，所以我才改了，两个手机以上我倒是觉得可以用 enumerate_devices 方法列出所有设备，然后让用户进行选择

**Comment by lyxhh** [comment]
可以考虑，但是这个并不是Bug，如果没有其他的 请允许我关闭这个issue

**Comment by lyxhh** [comment]
并且如果更改了frida端口 就一定要forward了，既然都要forward 就没必要改了哈。
