### ISSUE TITLE
[ERROR] frida-server No Running or port no forward....please check

### ISSUE THREAD

**Issue by fzts** [lyxhh/lxhToolHTTPDecrypt#4]
[11:19:56] [INFO] HTTP Decrypt running at http://127.0.0.1:8088
 * Serving Flask app "globalenv" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
[11:19:58] [ERROR] frida-server No Running or port no forward....please check.

你好，frida正常运行，已经进行端口转发，仍然不能使用，请问如何解决，多谢

**Comment by lyxhh** [comment]
转发之后多刷新几次也还是一样？------------------ 原始邮件 ------------------
发件人: "Qoo"<notifications@github.com>
发送时间: 2019年5月11日(星期六) 中午11:27
收件人: "lyxhh/lxhToolHTTPDecrypt"<lxhToolHTTPDecrypt@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [lyxhh/lxhToolHTTPDecrypt] [ERROR] frida-server No Running or port noforward....please check (#4)



[11:19:56] [INFO] HTTP Decrypt running at http://127.0.0.1:8088
  
Serving Flask app "globalenv" (lazy loading)
 
Environment: production
 WARNING: Do not use the development server in a production environment.
 Use a production WSGI server instead.
 
Debug mode: off
 [11:19:58] [ERROR] frida-server No Running or port no forward....please check.
  
你好，frida正常运行，已经进行端口转发，仍然不能使用，请问如何解决，多谢
 
&mdash;
